[package]
name = "proj_fs"
version = "0.1.0"
authors = ["renyuneyun (Rui ZHAO) <renyuneyun@gmail.com>"]
edition = "2018"

[dependencies]
bimap = "0.4"
dirs = "2.0"
env_logger = "0.7"
fuse_mt = "0.5"
lazy_static = "1.4"
libc = "0.2"
log = "0.4"
mime_guess = "2.0"
seahash = "3.0"
time = "0.1"

